name: Build and Deploy Node.js App to Azure Web App

on:
  push:
    branches:
      - main  # Change this if your default branch is different

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Make sure this matches your runtime

      - name: Install dependencies
        run: npm install

      - name: Build (if needed)
        run: echo "No build step for backend-only Node app"

      - name: Zip project
        run: Compress-Archive -Path * -DestinationPath app.zip

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: be-productive-plus  # Replace with your actual app name (without the region stuff)
          slot-name: production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: app.zip
